<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Jellyfin.Plugin.NoirMode.Core\Jellyfin.Plugin.NoirMode.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Common" Version="10.11.10" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.10" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <None Remove="Configuration\noirVideoPage.js" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\noirVideoPage.js" />
  </ItemGroup>

</Project>
